# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unlog < Formula
  desc "Unravel your logs — CLI log analysis tool"
  homepage "https://github.com/oxforge/unlog"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oxforge/unlog/releases/download/v0.1.2/unlog_0.1.2_darwin_amd64.tar.gz"
      sha256 "63bdb39405f0019419fc083da64df3233034f4af4a58dfe520e551edfbe139d0"

      define_method(:install) do
        bin.install "unlog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oxforge/unlog/releases/download/v0.1.2/unlog_0.1.2_darwin_arm64.tar.gz"
      sha256 "f4c103d764d96ccac426d8aa47f4adef0a048f3c0b14c7e4d4d8aea975509c6f"

      define_method(:install) do
        bin.install "unlog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oxforge/unlog/releases/download/v0.1.2/unlog_0.1.2_linux_amd64.tar.gz"
      sha256 "48e0afe0c62b4e42c9f81f49426c2e7c5b928ca0590e9070963ed5f3ccee8f28"
      define_method(:install) do
        bin.install "unlog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oxforge/unlog/releases/download/v0.1.2/unlog_0.1.2_linux_arm64.tar.gz"
      sha256 "1479335c46859a68b027fa3f9dc9b744c3103dd54c7ce6ad560683571cee5b0a"
      define_method(:install) do
        bin.install "unlog"
      end
    end
  end

  test do
    system "#{bin}/unlog", "version"
  end
end
