# This file was generated by GoReleaser. DO NOT EDIT.
cask "unlog" do
  name "unlog"
  desc "Unravel your logs — CLI log analysis tool"
  homepage "https://github.com/oxforge/unlog"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unlog"

  on_macos do
    on_intel do
      url "https://github.com/oxforge/unlog/releases/download/v#{version}/unlog_#{version}_darwin_amd64.tar.gz"
      sha256 "5cbb844bea0c366a6285809d6019d111e3482a2776974c82c649ccacb1598ed3"
    end
    on_arm do
      url "https://github.com/oxforge/unlog/releases/download/v#{version}/unlog_#{version}_darwin_arm64.tar.gz"
      sha256 "d4d367a24e86f1aedd76272c82e75923ad1b39443dd4275022bd7809024e3e75"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oxforge/unlog/releases/download/v#{version}/unlog_#{version}_linux_amd64.tar.gz"
      sha256 "69cd0975352a2d113eb95a1b271efafb77ab23cc7faac972708072101b3551b3"
    end
    on_arm do
      url "https://github.com/oxforge/unlog/releases/download/v#{version}/unlog_#{version}_linux_arm64.tar.gz"
      sha256 "b7cfc427f17301320bd826af701b19e2fb4bb7f3ee453e0de22655882fb0009a"
    end
  end

  # No zap stanza required
end
