# This file was generated by GoReleaser. DO NOT EDIT.
cask "unlog" do
  name "unlog"
  desc "Unravel your logs — CLI log analysis tool"
  homepage "https://github.com/oxforge/unlog"
  version "0.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unlog"

  on_macos do
    on_intel do
      url "https://github.com/oxforge/unlog/releases/download/v#{version}/unlog_#{version}_darwin_amd64.tar.gz"
      sha256 "3f61e320e72fb019c7c761984dba309a47c7926fb0db11d28635b1147a0aafa4"
    end
    on_arm do
      url "https://github.com/oxforge/unlog/releases/download/v#{version}/unlog_#{version}_darwin_arm64.tar.gz"
      sha256 "acbe75fe548056ee55598ac3f78ab3aa6b7c7c5d9e28341926a75fe20238f4c8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oxforge/unlog/releases/download/v#{version}/unlog_#{version}_linux_amd64.tar.gz"
      sha256 "27fc844dba3527cd5049daecb59a72883cb5781775209f9aeafbdb630b4d7077"
    end
    on_arm do
      url "https://github.com/oxforge/unlog/releases/download/v#{version}/unlog_#{version}_linux_arm64.tar.gz"
      sha256 "2e48cfe79fdb347a55d614f1f1ede31dc5dac3b3dfbc4d900dfab043f4cf6996"
    end
  end

  # No zap stanza required
end
